version: '3.1'
services:
  app:
    container_name: apirest-app
    image: apirest-app
    restart: always
    ports:
      - "8000:8000"
    links:
      - db
  db:
    container_name: apirest-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: apirest
    ports:
      - "5432:5432"
      
