server:
  port: 8000  
spring:
  datasource:
    url: jdbc:postgresql://db:5432/apirest
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        
# docker run -d -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=root -e POSTGRES_DB=apirest --name apirest-db -p 5432:5432 postgres:latest