server:
  port: 8000
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apirest
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect