server:
  port: 8000  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apirest
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
        
# docker run -d -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=root -e POSTGRES_DB=apirest --name apirest-db -p 5432:5432 postgres:latest